config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :customers, only: %i[new create]
  resources :offices, only: %i[show edit update]
  get "/offices/:id/home", to: "offices#home", as: "office_home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "customers#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
# A Customer may represent an active customer or merely a prospective one.
# In either case, they are assigned to the sales Office for the state where
# they live.
# They should also be assigned a SalesPerson, i.e. a User with the Role of :sales,
# who is in the same Office.
#
# TODO: Since we are not really creating, confirming, and validating customers
# as part of this exercise, preventing duplicate entries seemed not worth the effort.
class Customer < ApplicationRecord
  belongs_to :office
  belongs_to :sales_person, optional: true, class_name: "User", foreign_key: "user_id"

  validates :name, presence: true

  # TODO: I used to have a nice gem for validating emails. valid_email2 I believe.
  # Does devise have an email validator we can steal?
  validates :email, presence: true

  # TODO: There's probably something similar for phones. International support adds a few wrinkles.
  validates :phone, presence: true

  # TODO: Again, there's definitely less hacky ways to do this. But quick and dirty for now.
  validates :state, presence: true, us_state: true

  # assume that the UI only allowed the user to post a valid state, i.e,
  # one that we have an office for, so this hook _shouldn't_ fail on a normal case.
  before_validation -> { self.office = Office.find_by(state: state) }, on: :create

  scope :by_state, ->(state) { where(state: state) }
  scope :by_sales_person, ->(user) { where(sales_person: user) }
  scope :unassigned, -> { where(sales_person: nil) }

  def assign_sales_person!(user)
    raise ArgumentError, "User #{user.email} cannot be assigned to customer #{name}" unless user.has_role?(:sales, office)

    self.sales_person = user
    save!
  end
end

app/models/office.rb
# An Office represents the Customers and Employees (Users) for a single US state.
# Employees may be Managers or Sales People, depending on their Role. While in
# reality, there will likely be just a single manager to an office, nothing technically
# prevents there from being multiple.
class Office < ApplicationRecord
  resourcify

  validates :name, presence: true
  validates :state, presence: true, us_state: true

  has_many :users
  has_many :customers

  # QUESTION: can a user have more than 1 role?
  # probably not. We should remove one if we add another.
  # Seems like checking for that sort of thing would call for some kind of Policy object... hmmm.
  def add_manager(user)
    users << user
    user.add_role(:manager, self)
  end

  def add_sales_person(user)
    users << user
    user.add_role(:sales, self)
  end

  # HACK: assuming the first manager found is the primary manager
  def manager
    users.find { |u| u.has_role?(:manager, self) }
  end

  def managers
    users.select { |u| u.has_role?(:manager, self) }
  end

  def sales_people
    users.select { |u| u.has_role?(:sales, self) }
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
    polymorphic: true,
    optional: true

  validates :resource_type,
    inclusion: {in: Rolify.resource_types},
    allow_nil: true

  scopify
end

app/models/user.rb
# Users represent Employees in an Office.
# A User with the role of :sales can have many associated Customers that are
# also associated to the same office. The Customers will be manually assigned
# by a User in the same Office with the :manager role.
# An :admin Role also exists, but is reserved for debugging purposes at the moment
# and may be removed in the future.
class User < ApplicationRecord
  rolify

  # Just doing the bare minimum for devise here for testing purposes.
  # Some test users can be created via rake db:seed in the dev env.
  devise :database_authenticatable, :validatable, :timeoutable

  belongs_to :office, optional: true
  has_many :customers, inverse_of: :sales_person
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  after_action :verify_authorized, unless: :devise_controller?

  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError, with: :handle_not_authorized

  private

  def handle_not_authorized
    flash[:notice] = "You are not authorized to perform this action."
    redirect_to root_path
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!, except: %i[new create]

  # GET /customers/new
  def new
    @customer = Customer.new
    authorize @customer
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)
    authorize @customer
    respond_to do |format|
      if @customer.save
        format.html { redirect_to office_home_path(@customer.office), notice: "Thank you for your interest in our services. Someone from our local office will be contacting you shortly." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def customer_params
    params.require(:customer).permit(:name, :email, :phone, :state)
  end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :authenticate_user!, except: %i[home]
  before_action :set_office, only: %i[home show edit update]
  before_action :authorize_for_office, only: %i[home show edit update]

  # GET /offices/1/home
  def home
  end

  # GET /offices/1 or /offices/1.json
  def show
  end

  # GET /offices/1/edit
  def edit
  end

  # PATCH/PUT /offices/1 or /offices/1.json
  def update
    respond_to do |format|
      if @office.update(office_params)
        format.html { redirect_to office_url(@office), notice: "Office was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_office
    @office = Office.find(params[:id])
  end

  def authorize_for_office
    authorize @office
  end

  # Only allow a list of trusted parameters through.
  def office_params
    params.require(:office).permit(:name, :state)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, class: "contents") do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :state %>
    <%= form.text_field :state, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/customers/new.html.erb
<div class="container mx-auto my-5 p-1 md:w-2/3 w-full shadow-xl rounded bg-white">
  <%= turbo_frame_tag :root_frame do %>
    <div class="mx-auto my-5 p-1 md:w-2/3 w-full">
      <h1 class="font-bold text-2xl">Request for Information</h1>

      <header class="my-5 p-1">
      Enter your contact information in the form below, and one of our local agents will
      respond personally as soon as possible to answer all of your questions.
      </header>

      <%= render "form", customer: @customer %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Leads</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-slate-800">
    <div class="container mx-auto p-1">
      <div class="flex justify-between w-full">
        <div class="flex-2">
          <a href="<%= root_path %>">
            <h1 class="font-bold text-4xl text-white">Crimson Permanent Assurance</h1>
          </a>
        </div>
        <div class="flex-1 text-right self-center text-white">
          <% if current_user %>
            <%= link_to "Log Out (#{current_user.email})", destroy_user_session_path, 'data-turbo-method': :delete %>
          <% else %>
            <%= link_to "Log In", new_user_session_path %>
          <% end %>
        </div>
      </div>
      <div class="container mx-auto my-5 p-6">
        <% if notice || alert %>
          <div class="container mx-auto my-5 p-1 md:w-2/3 w-full shadow-xl rounded bg-white">
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/offices/_form.html.erb
<%= form_with(model: office, class: "contents") do |form| %>
  <% if office.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(office.errors.count, "error") %> prohibited this office from being saved:</h2>

      <ul>
        <% office.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :state %>
    <%= form.text_field :state, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/offices/_office.html.erb
<div id="<%= dom_id office%>" class="flex flex-col">
  <p class="my-3 flex-auto">
    <strong class="font-medium mb-1">Name:</strong>
    <%= office.name %>
  </p>

  <p class="my-3 flex-auto">
    <strong class="font-medium mb-1">State:</strong>
    <%= office.state %>
  </p>
</div>

app/views/offices/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing office</h1>

  <%= render "form", office: @office %>

  <%= link_to "Show this office", @office, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/offices/home.html.erb
<div class="container mx-auto my-5 p-1 md:w-2/3 w-full shadow-xl rounded bg-white">
  <%= turbo_frame_tag :root_frame do %>
    <div class="mx-auto my-5 p-1 md:w-2/3 w-full flex">
      <div class="mx-auto w-2/3">
        <% if notice.present? %>
          <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
        <% end %>

        <p class="my-5 font-medium">Your local agency is</p>
        <%= render @office %>

        <div class="my-5">
          <a href="<%= root_path %>" data-turbo-frame="_top">
            <button class="bg-blue-600 hover:bg-blue-700 rounded-lg px-5 py-3 text-white text-sm leading-5 font-semibold">Home</button>
          </a>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/offices/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @office %>

    <%= link_to 'Edit this office', edit_office_path(@office), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>